package bo;

import G.R;
import G.aM;
import G.be;
import V.a;
import aP.dd;
import bH.D;
import bn.a;
import com.efiAnalytics.ui.bV;
import com.efiAnalytics.ui.bc;
import com.efiAnalytics.ui.do;
import com.efiAnalytics.ui.et;
import com.efiAnalytics.ui.fh;
import com.efiAnalytics.ui.s;
import com.efiAnalytics.ui.u;
import com.efiAnalytics.ui.w;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import s.g;

public class b extends JPanel implements a, bc {
  w a = null;
  
  do b = new do();
  
  do c = new do();
  
  do d = new do();
  
  do e = new do();
  
  do f = new do();
  
  do g = new do();
  
  do h = new do();
  
  do i = new do();
  
  do j = new do();
  
  do k = new do();
  
  do l = new do();
  
  JComboBox m = new JComboBox();
  
  JCheckBox n = new JCheckBox(g.b("Scale for AFR"));
  
  private static String x = g.b("Naturally Aspirated");
  
  private static String y = g.b("Turbo");
  
  private static String z = g.b("Turbo w/Intercooler");
  
  private static String A = g.b("Supercharger");
  
  private static String B = g.b("Supercharger w/Intercooler");
  
  JComboBox o = new JComboBox();
  
  private static String C = g.b("Generate X & Y Bins");
  
  private static String D = g.b("Use existing X & Y Bins");
  
  public static int p = 0;
  
  public static int q = 1;
  
  public static int r = 2;
  
  private static double E = 0.06802721088435375D;
  
  private int F = p;
  
  s s = null;
  
  et t = null;
  
  String u = "";
  
  JDialog v = null;
  
  String w = "<html><body><center><h2>Table Generators</h2></center><br>The tables generated by this Table Generator are meant to assist<br>in creating an estimated rough starting point to start and <br>begin tuning a vehicle.<br>It is recommended that you use realistic values in this dialog<br>As you likely do not have values for your specific engine, find <br>real numbers for a similar engine. Guessed values can cause <br>disproportionate values and significantly scewed output.<br><br>There should be no expectation that this Table Generator will <br>produce a final or tuned table. The generated table should be<br>reviewed by a person understanding the risks of running an untuned engine <br>before use. EFI Analytics is not to be held liable for any resulting damages.<br><br><center><b>EFI Analytics, Inc</b> &copy; 2012</center></body></html>";
  
  public b(String paramString1, R paramR, String paramString2, s params, et paramet, int paramInt) {
    this.u = paramString1;
    this.s = params;
    this.t = paramet;
    this.F = paramInt;
    setLayout(new BorderLayout(8, 8));
    setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
    s s1 = fh.b(params);
    s1.q();
    this.a = new w(s1);
    be be = paramR.f(paramString2);
    aM aM = paramR.c(be.c());
    this.a.h().a(aM.v());
    add("Center", (Component)this.a);
    JPanel jPanel1 = new JPanel();
    jPanel1.setLayout(new BorderLayout(5, 5));
    JPanel jPanel2 = new JPanel();
    jPanel2.setLayout(new BorderLayout(5, 5));
    JPanel jPanel3 = new JPanel();
    jPanel3.setLayout(new GridLayout(0, 1, 4, 4));
    jPanel3.add(h());
    jPanel2.add("North", jPanel3);
    JPanel jPanel4 = new JPanel();
    jPanel4.setLayout(new BorderLayout());
    jPanel4.add("North", j());
    jPanel2.add("Center", jPanel4);
    jPanel2.setBorder(BorderFactory.createTitledBorder(a("Engine Characteristics")));
    jPanel1.add("Center", jPanel2);
    JPanel jPanel5 = new JPanel();
    jPanel5.setLayout(new BorderLayout());
    JPanel jPanel6 = new JPanel();
    jPanel6.setLayout(new BorderLayout(4, 4));
    jPanel6.add("Center", i());
    jPanel5.add("West", jPanel6);
    JPanel jPanel7 = new JPanel();
    jPanel7.setLayout(new GridLayout(1, 0, 4, 4));
    JButton jButton1 = new JButton(a("Generate"));
    jButton1.addActionListener(new c(this));
    jPanel7.add(jButton1);
    JButton jButton2 = new JButton(a("Apply") + " - " + this.u);
    jButton2.addActionListener(new d(this));
    jPanel7.add(jButton2);
    JButton jButton3 = new JButton(a("Cancel"));
    jButton3.addActionListener(new e(this));
    jPanel7.add(jButton3);
    jPanel5.add("East", jPanel7);
    add("South", jPanel5);
    add("West", jPanel1);
    f();
  }
  
  private JMenuBar c() {
    JMenuBar jMenuBar = new JMenuBar();
    JMenu jMenu = new JMenu(a("Help"));
    JMenuItem jMenuItem = new JMenuItem(a("About"));
    jMenuItem.addActionListener(new f(this));
    jMenu.add(jMenuItem);
    jMenuBar.add(jMenu);
    return jMenuBar;
  }
  
  private void d() {
    JFrame jFrame = dd.a().c();
    Image image = Toolkit.getDefaultToolkit().getImage(jFrame.getClass().getResource("resources/companyLogo.png"));
    ImageIcon imageIcon = new ImageIcon(image);
    JOptionPane.showMessageDialog(jFrame, this.w, a("About Table Generators"), 1, imageIcon);
  }
  
  private void e() {
    fh.a(this.a.g(), this.s);
    close();
  }
  
  private void f() {
    String str = a("txtIdleRpm", "700");
    this.b.setText(str);
    str = a("txtIdleMap", "35");
    this.c.setText(str);
    str = a("txtPkHpRpm", "");
    this.d.setText(str);
    str = a("txtMaxRpm", "");
    this.e.setText(str);
    str = a("txtPkHp", "");
    this.f.setText(str);
    str = a("txtPkHpMap", "100");
    this.g.setText(str);
    str = a("txtPkTqRpm", "");
    this.h.setText(str);
    str = a("txtPkTq", "");
    this.i.setText(str);
    str = a("txtPkTqMap", "100");
    this.j.setText(str);
    str = a("txtDisplacementCid", "");
    this.k.setText(str);
    str = a("txtDisplacementCc", "");
    this.l.setText(str);
    str = a("cBoost", x);
    this.m.setSelectedItem(str);
  }
  
  private void g() {
    b("txtIdleRpm", this.b.getText());
    b("txtIdleMap", this.c.getText());
    b("txtPkHpRpm", this.d.getText());
    b("txtMaxRpm", this.e.getText());
    b("txtPkHp", this.f.getText());
    b("txtPkHpMap", this.g.getText());
    b("txtPkTqRpm", this.h.getText());
    b("txtPkTq", this.i.getText());
    b("txtPkTqMap", this.j.getText());
    b("txtDisplacementCid", this.k.getText());
    b("txtDisplacementCc", this.l.getText());
    b("cBoost", this.m.getSelectedItem().toString());
  }
  
  private JPanel h() {
    JPanel jPanel = new JPanel();
    jPanel.setLayout(new BorderLayout(4, 4));
    jPanel.add("Center", new JLabel(g.b("Engine Type:"), 4));
    this.m.setEditable(false);
    this.m.addItem(x);
    this.m.addItem(y);
    this.m.addItem(z);
    this.m.addItem(A);
    this.m.addItem(B);
    jPanel.add("East", this.m);
    this.m.addActionListener(new g(this));
    return jPanel;
  }
  
  private JPanel i() {
    JPanel jPanel = new JPanel();
    jPanel.setLayout(new BorderLayout(4, 4));
    jPanel.add("Center", new JLabel(g.b("X & Y Axis:"), 4));
    this.o.setEditable(false);
    this.o.addItem(C);
    this.o.addItem(D);
    jPanel.add("East", this.o);
    return jPanel;
  }
  
  public boolean a() {
    String str = "";
    if (this.b.getText().equals("")) {
      str = str + "Idle RPM\n";
    } else if (this.c.getText().equals("")) {
      str = str + "IdleMap\n";
    } else if (this.d.getText().equals("")) {
      str = str + "Peak HP RPM\n";
    } else if (this.e.getText().equals("")) {
      str = str + "Maximum RPM\n";
    } else if (this.f.getText().equals("")) {
      str = str + "Peak HP\n";
    } else if (this.g.getText().equals("")) {
      str = str + "Peak HP MAP\n";
    } else if (this.h.getText().equals("")) {
      str = str + "Peak Torque RPM\n";
    } else if (this.i.getText().equals("")) {
      str = str + "Peak Torque\n";
    } else if (this.j.getText().equals("")) {
      str = str + "Peak Torque MAP";
    } else if (this.k.getText().equals("")) {
      str = str + "Displacement (CID)";
    } else if (this.l.getText().equals("")) {
      str = str + "Displacement (cc)";
    } 
    if (str.length() > 0) {
      bV.d("Please set values for:\n" + str, this);
      return false;
    } 
    boolean bool = this.m.getSelectedItem().equals(x);
    if (bool) {
      String str1 = "";
      if (this.g.e() > 102.0D)
        str1 = str1 + "Peak HP MAP\n"; 
      if (this.j.e() > 102.0D)
        str1 = str1 + "Peak Torque MAP\n"; 
      if (str1.length() > 0) {
        String str2 = a("The following have values greater than 100:") + "\n" + str1 + a("This is odd.") + "\n" + a("Are you sure you want to use these values?");
        if (!bV.a(str2, this, true))
          return false; 
      } 
    } 
    boolean bool1 = (this.m.getSelectedItem().equals(z) || this.m.getSelectedItem().equals(B)) ? true : false;
    double d1 = (this.g.e() > 101.3D) ? (bool1 ? 0.52D : 0.56D) : 0.46D;
    double d2 = (this.g.e() > 101.3D) ? (bool1 ? 0.56D : 0.6D) : 0.49D;
    double d3 = 941100.0D * d1 * this.i.e() / this.k.e() * 5252.0D;
    double d4 = 941100.0D * d2 * this.f.e() / this.k.e() * this.d.e();
    if (d4 > d3 * d2 / d1) {
      String str1 = a("Volumetric Efficency is higher at peak HP than at peak Torque.") + "\n" + a("These numbers do not appear to be realistic guesses.") + "\n" + a("Are you sure you want to use these values?");
      if (!bV.a(str1, this, true))
        return false; 
    } 
    if (this.d.e() < this.e.e() / 2.0D) {
      String str1 = a("Peak RPM seems very high compared to power RPM.") + "\n" + a("Are you sure you want to use these values?");
      if (!bV.a(str1, this, true))
        return false; 
    } 
    return true;
  }
  
  private String a(String paramString) {
    return g.b(paramString);
  }
  
  private JPanel j() {
    JPanel jPanel = new JPanel();
    jPanel.setLayout(new GridLayout(0, 1, 3, 3));
    k k = new k(this, "", new JLabel(""));
    k.a(new JLabel(g.b("RPM"), 0));
    k.a(new JLabel(g.b("MAP (kPa)"), 0));
    jPanel.add(k);
    k = new k(this, g.b("Idle"), new JLabel());
    k.a((JComponent)this.b);
    k.a((JComponent)this.c);
    jPanel.add(k);
    k = new k(this, g.b("Engine Redline"), new JLabel());
    k.a((JComponent)this.e);
    k.a(new JLabel());
    jPanel.add(k);
    k = new k(this, "", new JLabel("HP", 0));
    k.a(new JLabel(g.b("RPM"), 0));
    k.a(new JLabel(g.b("MAP (kPa)"), 0));
    jPanel.add(k);
    k = new k(this, g.b("Peak Power"), (JComponent)this.f);
    k.a((JComponent)this.d);
    k.a((JComponent)this.g);
    jPanel.add(k);
    k = new k(this, "", new JLabel("lbs-ft", 0));
    k.a(new JLabel(g.b("RPM"), 0));
    k.a(new JLabel(g.b("MAP (kPa)"), 0));
    jPanel.add(k);
    k = new k(this, g.b("Peak Torque"), (JComponent)this.i);
    k.a((JComponent)this.h);
    k.a((JComponent)this.j);
    jPanel.add(k);
    k = new k(this, "", new JLabel("   CID   ", 0));
    k.a(new JLabel(g.b("      cc      "), 0));
    jPanel.add(k);
    k = new k(this, g.b("Engine Displacement"), (JComponent)this.k);
    k.a((JComponent)this.l);
    jPanel.add(k);
    this.k.addKeyListener(new h(this));
    this.l.addKeyListener(new i(this));
    l l = new l(this);
    this.b.addFocusListener(l);
    this.c.addFocusListener(l);
    this.d.addFocusListener(l);
    this.e.addFocusListener(l);
    this.f.addFocusListener(l);
    this.g.addFocusListener(l);
    this.h.addFocusListener(l);
    this.i.addFocusListener(l);
    this.j.addFocusListener(l);
    this.k.addFocusListener(l);
    this.l.addFocusListener(l);
    return jPanel;
  }
  
  private void k() {
    if (a())
      if (this.F == p) {
        l();
      } else if (this.F == q || this.F == r) {
        m();
      } else {
        bV.d("Undefined Table type.\nDon't know what to generate??", this);
      }  
  }
  
  private void l() {
    try {
      s s1 = this.a.g();
      s s2 = new s();
      s2.a(s1.getRowCount(), s1.getColumnCount());
      s2 = u.a(s2, 20.0D, 400.0D, this.b.e(), this.e.e());
      byte b1;
      for (b1 = 0; b1 < s2.getRowCount(); b1++) {
        for (byte b2 = 0; b2 < s2.getColumnCount(); b2++)
          s2.setValueAt(Double.valueOf(14.7D), b1, b2); 
      } 
      b1 = (this.m.getSelectedItem().equals(z) || this.m.getSelectedItem().equals(B)) ? 1 : 0;
      boolean bool = this.o.getSelectedItem().equals(D);
      if (!bool) {
        s s3 = u.a(s2, s1.getColumnCount(), s1.getRowCount(), this.b.e(), this.c.e(), this.d.e(), this.e.e(), this.f.e(), this.g.e(), this.h.e(), this.i.e(), this.j.e(), this.k.e(), b1, 1.0D);
        fh.a(s3, s1);
      } else {
        u.a(s1, s2, this.b.e(), this.c.e(), this.d.e(), this.f.e(), this.g.e(), this.h.e(), this.i.e(), this.j.e(), this.k.e(), b1, 1.0D);
      } 
      g();
    } catch (a a1) {
      D.a("Failed to generate VE Table", (Exception)a1, this);
    } 
  }
  
  private void m() {
    try {
      s s1 = this.a.g();
      s s2 = new s();
      s2.a(s1.getRowCount(), s1.getColumnCount());
      boolean bool = this.o.getSelectedItem().equals(D);
      if (!bool) {
        boolean bool1 = (this.m.getSelectedItem().equals(z) || this.m.getSelectedItem().equals(B)) ? true : false;
        s2 = u.a(s2, this.b.e(), this.c.e(), this.d.e(), this.e.e(), this.f.e(), this.g.e(), this.h.e(), this.i.e(), this.j.e(), bool1);
      } else {
        fh.a(s1, s2);
      } 
      double d = (this.F == r) ? E : 1.0D;
      s2 = u.a(s2, d);
      fh.a(s2, s1);
      g();
    } catch (a a1) {
      D.a("Failed to generate VE Table", (Exception)a1, this);
    } 
  }
  
  private String a(String paramString1, String paramString2) {
    if (this.t != null) {
      String str = this.t.a(paramString1);
      if (str != null && !str.equals(""))
        return str; 
    } 
    return paramString2;
  }
  
  private void b(String paramString1, String paramString2) {
    this.t.a(paramString1, paramString2);
  }
  
  public void close() {
    g();
    if (this.v != null)
      this.v.dispose(); 
  }
  
  public void a(Component paramComponent) {
    Window window = bV.b(paramComponent);
    if (window instanceof Frame) {
      Frame frame = (Frame)window;
      this.v = new JDialog(frame, a("Table Generator"));
    } else if (window instanceof JDialog) {
      JDialog jDialog = (JDialog)window;
      this.v = new JDialog(jDialog, a("Table Generator"));
    } else {
      this.v = new JDialog((Frame)null, a("Table Generator"));
    } 
    this.v.add("North", c());
    this.v.add("Center", this);
    this.v.addKeyListener(new j(this));
    this.v.enableInputMethods(true);
    this.v.add("North", c());
    this.v.pack();
    bV.a(paramComponent, this.v);
    this.v.setVisible(true);
  }
}


/* Location:              /home/rewrich/Downloads/TunerStudioMS/TunerStudioMS/!/bo/b.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */